application:
  user: swift
  pass: swift
  flickr_user_id: 57201620@N08
  flickr_api_key: 60797d68137146b4f9af1ed6e5abd215
  flickr_shared_secret: dc49c4022c5900f3
  personal_blog_url: http://cycleswift.wordpress.com/
development:
  env: development

production: 
  env: production

test: 
  env: test
