application:
  user: builder
  pass: buildhandmadecommunity
  flickr_user_id: 57201620@N08
  flickr_api_key: 60797d68137146b4f9af1ed6e5abd215
  flickr_shared_secret: dc49c4022c5900f3
  # chasmo's
  # flickr_user_id: 88116251@N00
  # flickr_api_key: ba31da6a16b01b8f30b6dbb9a6e70c29
  # flickr_shared_secret: 1776db9047fc768f
  personal_blog_url: http://cycleswift.wordpress.com/
  twitter_url: http://twitter.com/SwiftIndustries
  facebook_url: http://www.facebook.com/pages/SwiftIndustries/319490293426
  instagram_url: http://instagram.com/swiftindustries/
  store_host: http://ww6.aitsafe.com
  add_to_cart_path: /cf/addmulti.cfm
  store_userid: '87211780'
  review_cart_path: /cf/review.cfm?userid=
  google_analytics_id: UA-21808495-1

development:
  env: development

production:
  env: production

test:
  env: test
