javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/orbit.1.2/jquery.orbit.js
    - public/javascripts/farbtastic/farbtastic.js

stylesheets:
  common:
    - public/stylesheets/reset-min.css
    - public/stylesheets/base.css
    - public/stylesheets/type.css
    - public/stylesheets/pub.css
    - public/stylesheets/scaffold.css
    - public/stylesheets/form.css
    - public/stylesheets/hub.css
    - public/stylesheets/homes.css
    - public/stylesheets/slideshow.css
    - public/javascripts/orbit.1.2/orbit.css
    - public/javascripts/farbtastic/farbtastic.css
