javascripts:
  common:
    - public/javascripts/orbit.1.2/jquery.orbit.js

stylesheets:
  common:
    - public/stylesheets/reset-min.css
    - public/stylesheets/scaffold.css
    - public/stylesheets/swift.css
    - public/javascripts/orbit.1.2/orbit.css